export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const CREATE_NEW_NEWS_SUCCESS = "CREATE_NEW_NEWS_SUCCESS";
export const FETCH_ONE_NEWS_SUCCESS = "FETCH_ONE_NEWS_SUCCESS";

export const DELETE = "DELETE";