export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const CREATE_NEW_NEWS_SUCCESS = "CREATE_NEW_NEWS_SUCCESS";
export const FETCH_ONE_NEWS_SUCCESS = "FETCH_ONE_NEWS_SUCCESS";

export const DELETE = "DELETE";

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";